[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[dependencies]
prost = "0.13"
tokio = { version = "1.44", features = ["full"] }
tonic = "0.12"

[build-dependencies]
tonic-build = "0.12"
